project:
  type: website
  output-dir: docs

execute:
  cache: true
  freeze: auto
  warning: false

website:
  title: ""
  
  navbar:

      
    left:
      - text: "Predict model - White mold in soybean"
        href: index.qmd
      - text: "<i class='bi bi-box-arrow-in-right'></i> Data" 
      

        href: join_all_data.qmd
      - text: "<i class='bi bi-graph-up'></i> Analysis"
        menu:
          - text: "Organizing"
            href: organizing_dataset.qmd
          - text: "Weather data"
            href: weather_data.qmd
          - text: "Method 1"
            href: ipt.qmd
          - text: "Method 2"
            href: method.qmd
          - text: "Logistic model"
            href: logistic.qmd
          
    right:
      - icon: twitter
        href: https://twitter.com/monalisacdc
      - icon: github
        href: https://github.com/Monalisacdc
      - icon: linkedin
        href: https://www.linkedin.com/in/monalisa-de-c%C3%B3l-62a6b31b8/

format:
  html:
    css: styles.css
    toc: true  
    toc_depth: 3  
    toc_title: "Sumário"  
    toc_float:  
      collapsed: no  
      smooth_scroll: no  
    lib_dir: site_libs  
    self_contained: no  


editor: visual